services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: api-nestjs
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
    depends_on:
      - postgres
    networks:
      - db-network

volumes:
  postgres_data:

networks:
  db-network:
